### ISSUE TITLE
selected element(Module) is not an instance of UMLStereotype

### ISSUE THREAD

**Issue by shahabgohar** [nestfarm/staruml-nestjs#1]
Hi there
I am following the step [3.1](https://github.com/nestfarm/staruml-nestjs#31-create-modulefolder) and got this error
kindly look at the problem and provide guidance/help.
I would highly appreciate your response

Thank you
regards,
Shahab Gohar

**Comment by JoseLuisMorenoGomez** [comment]
Me too! Where is described the fixing of this error, please?

**Comment by Kawtarr** [comment]
me too

**Comment by harithachalandula12** [comment]
I too..Can you please tell me how to resolve it
